Repository appKom/capellini, pull requests merged in 2024-11, with the labels that each got.

#319 Update footer
  components/Footer.tsx
  components/Navbar.tsx
  lib/hooks/useTheme.ts
  package-lock.json
  package.json
  pages/index.tsx
Labels: frontend, styling

#342 ensure responsiveness
  components/Button.tsx
  components/Navbar.tsx
  components/theme/ThemeToggle.tsx
  pages/index.tsx
Labels: styling

#345 add try catch blocks for auth
  pages/api/auth/[...nextauth].ts
Labels: bug
