Repository appKom/capellini, pull requests merged in 2024-07, with the labels that each got.

#130 Created about page
  components/Navbar.tsx
  components/icons/icons/AdminIcon.tsx
  pages/about.tsx
Labels: enhancement, frontend

#128 Changed button colors
  components/Button.tsx
  tailwind.config.js
Labels: frontend

#127 Created landing page and added href prop to button component
  components/Button.tsx
  components/LoadingPage.tsx
  components/icons/illustrations/FestivitiesIllustration.tsx
  pages/apply.tsx
  pages/index.tsx
  styles/globals.css
Labels: enhancement, frontend

#132 fixed background colors on about page
  pages/about.tsx
Labels: styling

#133 check icon in period card if applied
  components/PeriodCard.tsx
  components/icons/icons/CheckBoxIcon.tsx
  components/icons/icons/CheckIcon.tsx
  pages/application/[period-id].tsx
Labels: feature, frontend

#137 Fixed redirect bug
  pages/apply.tsx
  pages/index.tsx
Labels: bug, frontend

#141 fix textarea width
  components/form/TextAreaInput.tsx
Labels: bug, frontend

#107 57 implement aws ses for application
  .env.local.template
  lib/types/types.ts
  package-lock.json
  package.json
  pages/api/applicants/index.ts
  utils/capitalizeFirstLetter.ts
  utils/sendEmail.ts
Labels: feature

#153 check if applicationperiod is over before deleting application
  pages/api/applicants/[period-id]/[id].ts
  pages/application/[period-id].tsx
Labels: frontend, backend

#56 27 lage algoritme for å matche personer og komite med intervjutider
  .github/workflows/algorithm.yml
  .vscode/settings.json
  algorithm/README.md
  algorithm/pyproject.toml
  algorithm/requirements.txt
  algorithm/src/Modellering.md
  algorithm/src/__init__.py
  algorithm/src/mip_matching/Applicant.py
  algorithm/src/mip_matching/Committee.py
  algorithm/src/mip_matching/TimeInterval.py
  algorithm/src/mip_matching/__init__.py
  algorithm/src/mip_matching/match_meetings.py
  algorithm/tests/ApplicantTest.py
  algorithm/tests/CommitteeTest.py
  algorithm/tests/TimeIntervalTest.py
  algorithm/tests/__init__.py
  algorithm/tests/mip_test.py
Labels: feature

#168 Fetch all ow-committees with one request
  pages/api/periods/ow-committees.ts
Labels: backend, refactoring

#170 Created AvailabilityIndicator component
  components/committee/Schedule.tsx
Labels: frontend, refactoring

#169 Created new ImportantNote component
  components/ImportantNote.tsx
  components/committee/CommitteeInterviewTimes.tsx
  components/committee/Schedule.tsx
Labels: frontend, refactoring

#154 Merged the two utils folders, and deleted unused types.ts file
  components/committee/Schedule.tsx
  components/committee/ScheduleColumn.tsx
  lib/utils/capitalizeFirstLetter.ts
  lib/utils/getBaseUrl.ts
  lib/utils/getTimeSlots.ts
  lib/utils/sendEmail.ts
  pages/api/applicants/index.ts
  types.ts
Labels: refactoring

#155 Removed preparation period
  lib/mongo/periods.ts
  lib/types/types.ts
  lib/utils/PeriodValidator.ts
  lib/utils/validators.ts
  pages/admin/index.tsx
  pages/admin/new-period.tsx
  pages/committee/index.tsx
Labels: refactoring

#171 Removed unused packages
  package-lock.json
  package.json
Labels: refactoring

#172 Rewrote some of the content on about page
  components/applicantoverview/ApplicantCard.tsx
  pages/about.tsx
Labels: frontend

#174 New component PageTitle
  components/PageTitle.tsx
  components/committee/CommitteeInterviewTimes.tsx
  lib/utils/PeriodValidator.ts
  pages/admin/new-period.tsx
  pages/application/[period-id].tsx
  pages/apply.tsx
  pages/committee/[period-id]/[committee]/index.tsx
Labels: frontend

#179 Using <Link> instead of router.push
  components/DropdownMenu.tsx
  components/Navbar.tsx
  components/PeriodCard.tsx
  components/TableCard.tsx
  components/committee/CommitteeCard.tsx
  pages/admin/index.tsx
Labels: frontend, refactoring

#166 Committees info page
  components/CommitteeAboutCard.tsx
  lib/types/types.ts
  pages/api/periods/ow-committees.ts
  pages/committees.tsx
  pages/index.tsx
  public/Online_svart_o.svg
Labels: feature, frontend, backend

#187 Add warning for ntnu emails
  components/form/ApplicationForm.tsx
  lib/utils/validateApplication.ts
Labels: feature

#183 Fix console errors
  components/Navbar.tsx
  components/PageTitle.tsx
  components/Table.tsx
  components/icons/icons/CheckIcon.tsx
  components/icons/illustrations/FestivitiesIllustration.tsx
  pages/committee/[period-id]/index.tsx
Labels: bug, frontend

#181 Refactor fetching logic
  components/ErrorPage.tsx
  components/applicantoverview/ApplicantsOverview.tsx
  lib/api/applicantApi.ts
  lib/api/periodApi.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/admin/[period-id]/index.tsx
  pages/application/[period-id].tsx
  pages/committee/[period-id]/[committee]/index.tsx
  pages/committee/[period-id]/index.tsx
Labels: frontend, refactoring

#191 change bankkom to bankom
  components/Navbar.tsx
  components/applicantoverview/ApplicantCard.tsx
  components/committee/CommitteeInterviewTimes.tsx
  components/form/ApplicationForm.tsx
  lib/types/next-auth.d.ts
  lib/utils/apiChecks.ts
  pages/api/auth/[...nextauth].ts
  pages/api/committees/applicants/[period-id]/[committee].ts
  pages/committee/index.tsx
Labels: refactoring

#196 use tanstack query for fetching of ow committees
  lib/api/committees.ts
  pages/admin/new-period.tsx
  pages/committees.tsx
Labels: frontend, refactoring

#200 Refactored how periods are fetched
  lib/api/periodApi.ts
  pages/apply.tsx
  pages/committee/index.tsx
  pages/committees.tsx
Labels: frontend, refactoring

#195 Backend validation for committee input
  lib/mongo/committees.ts
  lib/utils/validators.ts
  pages/api/committees/times/[period-id]/[committee].ts
  pages/api/committees/times/[period-id]/index.ts
Labels: feature, backend

#212 Fixed bug where ApplicantCard data is wrong
  pages/application/[period-id].tsx
Labels: bug, frontend

#202 useQuery in PeriodCard
  components/PeriodCard.tsx
Labels: frontend, refactoring

#208 using tanstack to fetch /applicants
  components/applicantoverview/ApplicantsOverview.tsx
  lib/api/applicantApi.ts
  pages/admin/[period-id]/index.tsx
  pages/application/[period-id].tsx
Labels: frontend, refactoring

#213 Use mutation for creating and deleting periods
  lib/api/periodApi.ts
  pages/admin/index.tsx
  pages/admin/new-period.tsx
Labels: frontend, refactoring

#223 fixed period loading bug
  pages/admin/index.tsx
Labels: bug, frontend

#220 created applicant email template
  lib/email/applicantEmailTemplate.ts
  lib/email/sendEmail.ts
  pages/api/applicants/index.ts
Labels: feature, refactoring, styling

#219 removed output from committee page
  pages/committees.tsx
Labels: frontend

#218 changed link to out own committee page
  pages/apply.tsx
Labels: frontend

#217 Using tanstack to create and delete applicant
  lib/api/applicantApi.ts
  pages/application/[period-id].tsx
Labels: frontend, refactoring

#226 will now get a warning if you try to leave when you have unsaved changes
  components/committee/CommitteeInterviewTimes.tsx
  lib/utils/unSavedChangesWarning.ts
Labels: feature, frontend

#227 Shows how many applicants a committee can fit with their available times
  components/committee/CommitteeInterviewTimes.tsx
Labels: feature, frontend

#221 removed adding 0 to start of day, and shortened all month prefixes
  lib/utils/dateUtils.ts
Labels: frontend

#201 backend application validation with period
  lib/utils/validators.ts
  pages/api/applicants/index.ts
Labels: backend

#232 Refactor committee page
  components/committee/SendCommitteeMessage.tsx
  lib/api/committees.ts
  lib/api/committeesApi.ts
  pages/admin/new-period.tsx
  pages/committee/[period-id]/[committee]/index.tsx
  pages/committees.tsx
Labels: frontend, refactoring

#231 Refactor applicant overview
  components/applicantoverview/ApplicantTable.tsx
  components/applicantoverview/ApplicantsOverview.tsx
  lib/types/types.ts
Labels: frontend
