Repository appKom/capellini, pull requests merged in 2024-08, with the labels that each got.

#242 Created SimpleTitle-component and reused it where we have titles
  components/PageTitle.tsx
  components/PeriodSkeleton.tsx
  components/Typography.tsx
  components/applicantoverview/ApplicantsOverview.tsx
  components/committee/CommitteeInterviewTimes.tsx
  components/committee/SendCommitteeMessage.tsx
  pages/404.tsx
  pages/_app.tsx
  pages/about.tsx
  pages/admin/[period-id]/index.tsx
  pages/admin/index.tsx
  pages/admin/new-period.tsx
  pages/application/[period-id].tsx
  pages/apply.tsx
  pages/committee/[period-id]/[committee]/index.tsx
  pages/committee/[period-id]/index.tsx
  pages/committee/index.tsx
  pages/committees.tsx
  pages/index.tsx
Labels: testing, frontend, refactoring

#243 moved application page to /apply/periodId
  components/PeriodCard.tsx
  components/committee/Schedule.tsx
  pages/apply/[period-id].tsx
  pages/apply/index.tsx
  pages/committee/[period-id]/[committee]/index.tsx
Labels: frontend

#234 Fixed email styling
  lib/email/applicantEmailTemplate.ts
Labels: styling, email

#250 npm audit fix
  package-lock.json
Labels: dependencies

#254 will hide applicants for committees before interviews
  lib/mongo/applicants.ts
Labels: backend

#239 changed bankkom type from english to norwegian
  components/applicantoverview/ApplicantCard.tsx
  components/applicantoverview/ApplicantsOverview.tsx
  components/form/ApplicationForm.tsx
  lib/types/types.ts
  lib/utils/toString.ts
  lib/utils/validators.ts
  pages/api/applicants/index.ts
Labels: refactoring

#255 252 shuffle committees and add tab for node committees
  components/CommitteeAboutCard.tsx
  lib/types/types.ts
  lib/utils/shuffleList.ts
  pages/committees.tsx
Labels: frontend, styling

#256 add interviewsplanned / applications
  components/committee/CommitteeInterviewTimes.tsx
Labels: frontend

#190 Meetings from DB is fetched, matched and sent to DB
  algorithm/bridge/fetch_applicants_and_committees.py
  algorithm/src/mip_matching/Applicant.py
  algorithm/src/mip_matching/Committee.py
  algorithm/src/mip_matching/TimeInterval.py
  algorithm/src/mip_matching/match_meetings.py
Labels: algorithm

#244 Feat: Applicants can now apply for only a optionalCommittee
  components/committee/Schedule.tsx
  lib/utils/validateApplication.ts
  lib/utils/validators.ts
Labels: frontend, backend

#268 Søkere kan ikke lenger bli tildelt overlappende intervjuer
  algorithm/src/mip_matching/match_meetings.py
  algorithm/tests/mip_test.py
Labels: bug, algorithm

#271 Fixed buggy removeCell resulting in numberOfInterviews not being updated on delete among other things
  components/committee/CommitteeInterviewTimes.tsx
Labels: frontend

#273 272 refactor committeeinterviewtimes
  components/committee/CommitteeInterviewTimes.tsx
Labels: frontend

#260 Button that sends out SMS and Email with interview times
  .env.local.template
  lib/mongo/applicants.ts
  lib/mongo/committees.ts
  lib/mongo/interviews.ts
  lib/mongo/periods.ts
  lib/sendInterviewTimes/fetchFunctions.ts
  lib/sendInterviewTimes/formatAndSend.ts
  lib/sendInterviewTimes/formatInterviewEmail.ts
  lib/sendInterviewTimes/formatInterviewSMS.ts
  lib/sendInterviewTimes/sendInterviewTimes.ts
  lib/sendInterviewTimes/sendSMS.ts
  lib/types/types.ts
  lib/utils/dateUtils.ts
  lib/utils/validators.ts
  package-lock.json
  package.json
  pages/admin/[period-id]/index.tsx
  pages/api/committees/times/[period-id]/index.ts
  pages/api/periods/send-interview-times/[period-id].ts
Labels: feature, backend

#277 Better responsive committee card
  components/CommitteeAboutCard.tsx
  pages/committees.tsx
Labels: frontend, styling

#284 Fixed bug where applicantCard is not displayed after applying
  pages/apply/[period-id].tsx
Labels: frontend

#286 Hide applicants 7 days after interview period
  components/applicantoverview/ApplicantsOverview.tsx
  lib/mongo/applicants.ts
  lib/types/types.ts
Labels: backend

#282 Add country code selection for application form
  components/form/ApplicationForm.tsx
  components/form/CustomPhoneInput.tsx
  components/form/SelectInput.tsx
  components/form/TextAreaInput.tsx
  components/form/TextInput.tsx
  lib/sendInterviewTimes/formatAndSend.ts
  package-lock.json
  package.json
Labels: frontend, styling

#296 Fixed bug where ApplicantCard was buggy
  pages/apply/[period-id].tsx
Labels: bug, frontend

#297 Add + in phone
  components/applicantoverview/ApplicantCard.tsx
  lib/utils/toString.ts
Labels: frontend

#301 fix: include optionalCommittees
  pages/committee/index.tsx
Labels: bug

#303 Expanded time slot to 18:00
  lib/utils/getTimeSlots.ts
Labels: frontend
